package calculadora;

import java.awt.Frame;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 * @author tomasbascal
 */
public class Calculadora extends javax.swing.JFrame {

ScriptEngineManager sem = new ScriptEngineManager();
ScriptEngine se = sem.getEngineByName("JavaScript");
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        lblOperacion = new javax.swing.JLabel();
        lblBtnMin = new javax.swing.JLabel();
        lblBtnClose1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnIgual = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnPorcentaje = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(252, 224, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setInheritsPopupMenu(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(330, 150));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 150));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(55, 62, 71));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResultado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 330, 44));

        lblOperacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOperacion.setForeground(new java.awt.Color(55, 62, 71));
        lblOperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 330, 40));

        lblBtnMin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBtnMin.setForeground(new java.awt.Color(255, 150, 77));
        lblBtnMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnMin.setText("●");
        lblBtnMin.setAlignmentY(0.0F);
        lblBtnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnMinMouseClicked(evt);
            }
        });
        jPanel1.add(lblBtnMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 20, 30));

        lblBtnClose1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBtnClose1.setForeground(new java.awt.Color(255, 0, 0));
        lblBtnClose1.setText("●");
        lblBtnClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBtnClose1MouseClicked(evt);
            }
        });
        jPanel1.add(lblBtnClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(249, 125, 125));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setInheritsPopupMenu(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(330, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(330, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIgual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnIgual.setForeground(new java.awt.Color(255, 221, 255));
        btnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc iwal.png"))); // NOI18N
        btnIgual.setText("=");
        btnIgual.setBorderPainted(false);
        btnIgual.setContentAreaFilled(false);
        btnIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIgual.setPreferredSize(new java.awt.Dimension(50, 50));
        btnIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnIgual.setRolloverEnabled(true);
        btnIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc iwal.png"))); // NOI18N
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel2.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        btn9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(55, 62, 71));
        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn9.setText("9");
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn9.setPreferredSize(new java.awt.Dimension(50, 50));
        btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn9.setRolloverEnabled(true);
        btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, -1));

        btnCE.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCE.setForeground(new java.awt.Color(55, 62, 71));
        btnCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnCE.setText("CE");
        btnCE.setBorderPainted(false);
        btnCE.setContentAreaFilled(false);
        btnCE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCE.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCE.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnCE.setRolloverEnabled(true);
        btnCE.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });
        jPanel2.add(btnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 20, 60, -1));

        btnPorcentaje.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        btnPorcentaje.setForeground(new java.awt.Color(55, 62, 71));
        btnPorcentaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnPorcentaje.setText("%");
        btnPorcentaje.setBorderPainted(false);
        btnPorcentaje.setContentAreaFilled(false);
        btnPorcentaje.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPorcentaje.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPorcentaje.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnPorcentaje.setRolloverEnabled(true);
        btnPorcentaje.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorcentajeActionPerformed(evt);
            }
        });
        jPanel2.add(btnPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        btnDividir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(55, 62, 71));
        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnDividir.setText("/");
        btnDividir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDividir.setContentAreaFilled(false);
        btnDividir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDividir.setPreferredSize(new java.awt.Dimension(50, 50));
        btnDividir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnDividir.setRolloverEnabled(true);
        btnDividir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel2.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        btnMultiplicar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnMultiplicar.setForeground(new java.awt.Color(55, 62, 71));
        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnMultiplicar.setText("x");
        btnMultiplicar.setBorderPainted(false);
        btnMultiplicar.setContentAreaFilled(false);
        btnMultiplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMultiplicar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnMultiplicar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnMultiplicar.setRolloverEnabled(true);
        btnMultiplicar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel2.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        btnSumar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(55, 62, 71));
        btnSumar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnSumar.setText("+");
        btnSumar.setBorderPainted(false);
        btnSumar.setContentAreaFilled(false);
        btnSumar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSumar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnSumar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnSumar.setRolloverEnabled(true);
        btnSumar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        btnRestar.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(55, 62, 71));
        btnRestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnRestar.setText("-");
        btnRestar.setBorderPainted(false);
        btnRestar.setContentAreaFilled(false);
        btnRestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRestar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnRestar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnRestar.setRolloverEnabled(true);
        btnRestar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        btnC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnC.setForeground(new java.awt.Color(55, 62, 71));
        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnC.setText("C");
        btnC.setBorderPainted(false);
        btnC.setContentAreaFilled(false);
        btnC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnC.setPreferredSize(new java.awt.Dimension(50, 50));
        btnC.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosa.png"))); // NOI18N
        btnC.setRolloverEnabled(true);
        btnC.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel2.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btn7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(55, 62, 71));
        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn7.setText("7");
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn7.setPreferredSize(new java.awt.Dimension(50, 50));
        btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn7.setRolloverEnabled(true);
        btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btn8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(55, 62, 71));
        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn8.setText("8");
        btn8.setBorderPainted(false);
        btn8.setContentAreaFilled(false);
        btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn8.setPreferredSize(new java.awt.Dimension(50, 50));
        btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn8.setRolloverEnabled(true);
        btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        btn6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(55, 62, 71));
        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn6.setText("6");
        btn6.setBorderPainted(false);
        btn6.setContentAreaFilled(false);
        btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn6.setPreferredSize(new java.awt.Dimension(50, 50));
        btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn6.setRolloverEnabled(true);
        btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btn5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(55, 62, 71));
        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn5.setText("5");
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn5.setPreferredSize(new java.awt.Dimension(50, 50));
        btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn5.setRolloverEnabled(true);
        btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        btn4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(55, 62, 71));
        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn4.setText("4");
        btn4.setBorderPainted(false);
        btn4.setContentAreaFilled(false);
        btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4.setPreferredSize(new java.awt.Dimension(50, 50));
        btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn4.setRolloverEnabled(true);
        btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        btn3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(55, 62, 71));
        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn3.setText("3");
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3.setPreferredSize(new java.awt.Dimension(50, 50));
        btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn3.setRolloverEnabled(true);
        btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        btn2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(55, 62, 71));
        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn2.setText("2");
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2.setPreferredSize(new java.awt.Dimension(50, 50));
        btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn2.setRolloverEnabled(true);
        btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        btn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(55, 62, 71));
        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn1.setText("1");
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1.setPreferredSize(new java.awt.Dimension(50, 50));
        btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn1.setRolloverEnabled(true);
        btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        btnPunto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPunto.setForeground(new java.awt.Color(55, 62, 71));
        btnPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btnPunto.setText(".");
        btnPunto.setBorderPainted(false);
        btnPunto.setContentAreaFilled(false);
        btnPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPunto.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPunto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btnPunto.setRolloverEnabled(true);
        btnPunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        btn0.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(55, 62, 71));
        btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn0.setText("0");
        btn0.setBorderPainted(false);
        btn0.setContentAreaFilled(false);
        btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn0.setPreferredSize(new java.awt.Dimension(50, 50));
        btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn calc 2.png"))); // NOI18N
        btn0.setRolloverEnabled(true);
        btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnrosaoscuro.png"))); // NOI18N
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        addNumber("7");
        btnIgual.doClick();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        addNumber("0");
        btnIgual.doClick();
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        addNumber("1");
        btnIgual.doClick();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       addNumber("2");
       btnIgual.doClick();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        addNumber("3");
        btnIgual.doClick();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
       addNumber("4");
       btnIgual.doClick();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       addNumber("5");
       btnIgual.doClick();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        addNumber("6");
        btnIgual.doClick();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        addNumber("8");
        btnIgual.doClick();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       addNumber("9");
       btnIgual.doClick();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
       lblOperacion.setText("");
       lblResultado.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
//Obtengo la operacion y le quito el ultimo elemento
        String texto = lblOperacion.getText().substring(0, lblOperacion.getText().length()-1);
//El condicional es por si no hay operacion que realizar
       if (texto.length()>=0) {
            lblOperacion.setText(texto);
        }
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorcentajeActionPerformed
       addNumber("%");
    }//GEN-LAST:event_btnPorcentajeActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
       addNumber("/");
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
       addNumber("*");
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
       addNumber("+");
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
       addNumber("-");
    }//GEN-LAST:event_btnRestarActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
    try {
        String res = se.eval(lblOperacion.getText()).toString();
        lblResultado.setText(res);
    } catch (ScriptException ex) {
        lblResultado.setText("Error de sintaxis");
    }

    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
       addNumber(".");
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void lblBtnClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnClose1MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblBtnClose1MouseClicked
private int x;
private int y;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
          Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x-x , point.y-y );
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        x= evt.getX();
        y= evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void lblBtnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBtnMinMouseClicked
        this.setState(Frame.ICONIFIED);
        System.out.println("hiuhi");
    }//GEN-LAST:event_lblBtnMinMouseClicked
    public void addNumber(String digito){
        lblOperacion.setText(lblOperacion.getText()+digito);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnPorcentaje;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBtnClose1;
    private javax.swing.JLabel lblBtnMin;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables
}
